const language = {
  "zh-CN": {
    nickName: "管理员",
    title: "当前语言：中文",
    welcome: "欢迎使用开源的：vue3-ts-vite-admin",
    btnZh: "切换中文",
    btnEn: "切换英文",
    首页: "首页",
    主题管理: "主题管理",
    表格管理: "表格管理",
    路由管理: "路由管理",
    国际化: "国际化",
    微前端: "微前端",
    地图: "地图",
    富文本编辑器: "富文本编辑器",
    iframe通信: "iframe通信",
    大屏展示: "大屏展示",
    表单: "表单",
    联系作者: "联系作者",
    其他模块: "其他模块",
    full: "全屏",
    signOut: "退出登录",
    设置: "设置",
    个人信息: "个人信息",
    修改信息: "修改信息",
    普通账号登录: "普通账号登录",
    管理员账号登录: "管理员账号登录",
    版本号: "版本号",
    请输入普通账号: "请输入普通账号",
    请输入管理员账号: "请输入管理员账号",
    请输入密码: "请输入密码",
    登录: "登录",
    子应用1: "子应用1",
    子应用2: "子应用2",
    图书详情: "图书详情",
  },
  "en-US": {
    nickName: "adminer",
    title: "current language: English",
    welcome: "welcome to use open source vue3-ts-vite-admin",
    btnZh: "change Chinese",
    btnEn: "change English",
    首页: "Home",
    主题管理: "Theme Manage",
    表格管理: "Table Manage",
    路由管理: "Router Manage",
    国际化: "International",
    微前端: "Micro Web",
    地图: "Map",
    富文本编辑器: "Editor",
    iframe通信: "iframe Message",
    大屏展示: "Screen",
    表单: "Form",
    联系作者: "Contact Author",
    其他模块: "Other",
    full: "Full Screen",
    signOut: "Sign Out",
    设置: "Setting",
    个人信息: "User Info",
    修改信息: "Modify Info",
    普通账号登录: "Common Account",
    管理员账号登录: "Admin Account",
    版本号: "version",
    请输入普通账号: "input common account",
    请输入管理员账号: "input admin account",
    请输入密码: "input password",
    登录: "Login in",
    子应用1: "SubApp One",
    子应用2: "SubApp Two",
    图书详情: "Book Detail",
  },
};
export default language;
